### ISSUE TITLE
Tags für Blog-Einträge

### ISSUE THREAD

**Issue by mbaechtold** [stevenpi/Link.Python.Django.DiyBlog#6]
Auf einem Blog-Eintrag können beliebig viele Tags hinerlegt werden.
Beim Klick auf einen Tag werden alle Blog-Einträge angezeigt, die mit diesem Tag versehen worden sind.

**Comment by mbaechtold** [comment]
Auch hier kannst du zuerst auf https://djangopackages.org/grids/g/tagging/ schauen, ob das Problem schon jemand gelöst hat und für Django ein entsprechendes Addon programmiert hat. Dabei geht es auch darum, die bestehenden Addons kurz anzuschauen und auf Aktualität und Kompabilität mit Python 3 und Django 2 zu prüfen.

**Comment by stevenpi** [comment]
Resolved by f53da87d94e71244f6ce94440278574d206ce9a8
